### ISSUE TITLE
为cqhttp适配器添加post_type为message_sent的事件的支持

### ISSUE THREAD

**Issue by sckiyo** [AliceBotProject/alicebot#145]
onebot11本身没有这个类型的事件，但是go-cqhttp以及现在流行的onebot11实现会有这个，就只是把message事件的post_type改成了message_sent。

现在的cqhttp适配器匹配事件是找post_type+"_type"这个字段，但是对于message_sent事件，现在的onebot11实现基本不会有message_sent_type这个字段，只会和message事件一样提供message_type字段。

所以现在仅简单的通过CQHTTPAdapter.add_event_model来为message_sent类型添加自定义事件的话，只能添加例如MessageSentEvent，但是像PrivateMessageSentEvent、GroupMessageSentEvent这些，因为缺少message_sent_type，就没办法了。大概要改CQHTTPAdapter中对事件的匹配规则。

我也试了给一个onebot11实现提建议添加message_sent_type字段，但是被认为这个字段是不标准的。所以希望能不能为cqhttp适配器添加官方的对post_type为message_sent的事件的支持。

**Comment by st1020** [comment]
已经在 #146 中修改判断逻辑，优先取 `("message_type", "notice_type", "request_type", "meta_event_type")` 这四种已知的 key，应该可以兼容 message_sent 事件。
