### ISSUE TITLE
这是一个小建议

### ISSUE THREAD

**Issue by Admsec** [AliceBotProject/alicebot#26]
1. 可不可以增加一个超级管理员配置文件字段 master，通过 self.bot.master 快速访问，很多管理性的插件都要用到此配置
2. 能不能增加一个快速修改配置文件的方法，可以让超级管理员在QQ就发消息就可以修改配置文件，比如把一个插件的功能限制仅在一个列表里面的群可以启用，超级管理员通过QQ给机器人发消息就可以动态修改该列表

**Comment by HsiangNianian** [comment]
Q1
---

> 可不可以增加一个超级管理员配置文件字段 master，通过 self.bot.master 快速访问，很多管理性的插件都要用到此配置

A1
---

![image](https://user-images.githubusercontent.com/44714368/230579049-5ee8c6bb-9be8-49f4-8e9d-ded21ef0be93.png)


Q2
---

> 能不能增加一个快速修改配置文件的方法，可以让超级管理员在QQ就发消息就可以修改配置文件，比如把一个插件的功能限制仅在一个列表里面的群可以启用，超级管理员通过QQ给机器人发消息就可以动态修改该列

A2
---

这其实应该是插件编写时应该考虑的事情，也就是说如何配置插件权限和使用范围应该由插件作者自行编写
