### ISSUE TITLE
用于插件中的自定义配置在插件执行过程中被修改应如何保存？

### ISSUE THREAD

**Issue by Matt-wzy** [AliceBotProject/alicebot#32]
感谢您制作了alicebot，它对新手真的很友好。但是我遇上了个问题，config.toml中配置自定义字段，例如`group_list={"grout1":string1,"group2":string2}`,在使用过程中需要增加键值group3:string3进去，在程序中self.bot.config.group_list['group3']=string3之后关闭程序，发现其内容没有被写入到文件中，但是程序运行状态时却是能正确读出修改后的配置，请问这种情况下是程序bug还是本就没有设计修改配置后的保存功能？我看说明文档中也没有提示相关的内容。期待回复。

**Comment by st1020** [comment]
Bot 的 config 字段和配置文件之间是“单向绑定”的，也就是说配置文件的更新会反映在 config 上（如果开启了热重载的话），而反之则不成立。因此，如果你确实需要在运行时修改配置文件的话，请手动修改配置文件（如使用 [tomlkit](https://github.com/sdispater/tomlkit)、[tomli-w](https://github.com/hukkin/tomli-w) 等）。

但是，这种做法往往并非是你想要达到的功能的最佳实践，因为修改配置文件后触发的热重载会消耗一定的性能，并且可能会导致对消息的应答在热重载期间短暂的不可用，关闭热重载的话则需要手动维护 config 和配置文件的一致性。此外，toml 格式文件在修改时保持格式也是一个问题（[tomlkit](https://github.com/sdispater/tomlkit) 支持修改 toml 后保持格式）。

大部分情况下，对于需要在运行时修改的数据，建议使用 [状态存储](https://docs.alicebot.dev/guide/plugin-advanced.html#%E7%8A%B6%E6%80%81%E5%AD%98%E5%82%A8)，并在修改后手动序列化为 json 文件。

当然，如果确有需要，在运行时手动修改配置文件也是可行的选择，但请务必注意数据一致性和热重载相关问题。

**Comment by Matt-wzy** [comment]
非常感谢,经过考虑之后我打算用 configparser 来进行相关的需求实现了.
