### ISSUE TITLE
Re: Adding the Footer into the AliceBot Website

### ISSUE THREAD

**Issue by ConnectBhawna** [AliceBotProject/alicebot#35]
I've gone through the site but couldn't find the footer on the AliceBot page. If you're interested in adding it, please let me know. I'd be happy to work in this task.

Thank you!

**Comment by st1020** [comment]
Thanks for your advice! There is actually have a footer on the [home page](https://docs.alicebot.dev/). And I think it might be unnecessary to add a footer to the guide page.
