### ISSUE TITLE
TG的协议适配是否有时间节点呢

### ISSUE THREAD

**Issue by getSilver** [AliceBotProject/alicebot#51]

**Comment by st1020** [comment]
目前还没有准确的时间节点，保守估计的话可能会作为明年的任务，但欢迎任何相关的贡献。

**Comment by zizhengWong** [comment]
> 目前还没有准确的时间节点，保守估计的话可能会作为明年的任务，但欢迎任何相关的贡献。

我在OSPP上看到了这个项目，有一些相关的开发经验，想请问一下目前该项目是否已有同学在进行中？如若没有，我可以负责这个工作
