### ISSUE TITLE
关于 Pypi 仓库中的一些问题

### ISSUE THREAD

**Issue by Larry0716** [AliceBotProject/alicebot#94]
我根据「[快速上手 | AliceBot](https://docs.alicebot.dev/guide/quick-start.html)」一文中讲述的方法，使用了如下命令安装的 Alicebot 轮子以及其 Mirai Adaptor：

```bash
pip install alicebot
pip install alicebot-adapter-mirai
```

然后当我 `from alicebot import Bot` 的时候，出现了如下问题：

```python
>>> from alicebot import Bot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "%appdata%\..\Local\Programs\Python\Python38\lib\site-packages\alicebot\__init__.py", line 14, in <module>
    from alicebot.adapter import Adapter
  File "%appdata%\..\Local\Programs\Python\Python38\lib\site-packages\alicebot\adapter\__init__.py", line 23, in <module>
    from alicebot.utils import is_config_class
  File "%appdata%\..\Local\Programs\Python\Python38\lib\site-packages\alicebot\utils.py", line 60, in <module>
    StrOrBytesPath: TypeAlias = Union[str, bytes, PathLike[str], PathLike[bytes]]
TypeError: 'ABCMeta' object is not subscriptable
```

然后当我打开文件 `alicebot\utils.py` 的时候，发现其内容与仓库中的代码不一致，具体地说，仓库中所编写的内容为：

```python
# At Line 60
StrOrBytesPath: TypeAlias = Union[str, bytes, "PathLike[str]", "PathLike[bytes]"]
```

而 pip 下下来的是：

```python
# At Line 60
StrOrBytesPath: TypeAlias = Union[str, bytes, PathLike[str], PathLike[bytes]]
```

我不是很清楚这个情况是不是只有在 Python 3.8.X 系列版本中出现的问题，但是它确确实实出现在了使用 Python 3.8.X 的 PC 上。

环境配置如下：

- Windows 7 x64 Service Pack 1
- Python 3.8.10 
- pip 21.1.1

由于我不是专业的，可能有一些地方说的不是很严谨，也请大家多多海涵 ;)

**Comment by st1020** [comment]
是的，这是一个已知问题，在之前的代码中错误使用了 Python 3.9 中的新特性 ([bpo-38994](https://github.com/python/cpython/pull/17498))，而这个问题已经在最新的主线中被修复了。

你可以根据需要使用以下任意方案解决这个问题：

1. 使用 Python 3.9 及以上版本
2. 等待 AliceBot 发布新的版本
3. 使用仓库中的新代码手动构建新的 AliceBot 包
